
import Head from 'next/head'

import Image from "next/image";
import styles from '../styles/Home.module.css'
import AboutUs from './AboutUs';
import CarouselMain from './CarouselMain';
import Collection from './Collection';
import Footer from './Footer';

import Nav from './Nav'

export default function Home() {
  return (
    <div >
      <Head>
        <title>BlockMarket Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <Nav />
     
        <CarouselMain />
     

      <Collection />
      <AboutUs/>
      <Footer/>

      

     
    </div>
  )
}
